### ISSUE TITLE
Few example queries fail to build with "Type checking error: Type mismatch in map...."

### ISSUE THREAD

**Issue by mrayva** [dbtoaster/dbtoaster-backend#88] opened 2018-04-05 02:42 UTC
Ubuntu 16.04 SCALA VERSION 2.10.7 SBT VERSION 1.1.1 gcc  5.4.0 20160609

1.

[info] Running ddbt.Compiler -l cpp -o bin/rs_example1.hpp -c bin/rs_example1.exe -x -xd bin -F -O3 -F -COMPILE-WITH-STATIC /usr/local/opt/dbtoaster/examples/queries/simple/rs_example1.sql
[error] java.lang.RuntimeException: Type checking error: Type mismatch in map RESULT_mS1(int)[][result_mss_b: int]<Local> of type int and RHS expression AggSum([result_mss_b: int],
[error]   (R(long)[][r_a: int, result_mss_b: int]<Local> * r_a: int)
[error] ): long of type long
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$typeStmt$1(TypeCheck.scala:334)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at scala.collection.immutable.List.map(List.scala:284)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:347)
[error] 	at scala.collection.immutable.List.map(List.scala:288)
[error] 	at ddbt.frontend.TypeCheck$.typeCheck(TypeCheck.scala:347)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:372)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:12)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.Compiler$.codegen(Compiler.scala:366)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.lib.Utils$.ns(Utils.scala:40)
[error] 	at ddbt.Compiler$.compile(Compiler.scala:542)
[error] 	at ddbt.Compiler$.main(Compiler.scala:597)
[error] 	at ddbt.Compiler.main(Compiler.scala)
[error] 
[success] Total time: 2 s, completed Apr 4, 2018 10:12:44 PM

2. 
[info] Running ddbt.Compiler -l cpp -o bin/rs_ineqwithnestedagg.hpp -c bin/rs_ineqwithnestedagg.exe -x -xd bin -F -O3 -F -COMPILE-WITH-STATIC /usr/local/opt/dbtoaster/examples/queries/simple/rs_ineqwithnestedagg.sql
[error] java.lang.RuntimeException: Type checking error: Type mismatch in map COUNT_mS2(int)[][r_a: int, r_b: int]<Local> of type int and RHS expression R(long)[][r_a: int, r_b: int]<Local> of type long
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$typeStmt$1(TypeCheck.scala:334)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at scala.collection.immutable.List.map(List.scala:284)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:347)
[error] 	at scala.collection.immutable.List.map(List.scala:288)
[error] 	at ddbt.frontend.TypeCheck$.typeCheck(TypeCheck.scala:347)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:372)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:12)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.Compiler$.codegen(Compiler.scala:366)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.lib.Utils$.ns(Utils.scala:40)
[error] 	at ddbt.Compiler$.compile(Compiler.scala:542)
[error] 	at ddbt.Compiler$.main(Compiler.scala:597)
[error] 	at ddbt.Compiler.main(Compiler.scala)
[error] 
[success] Total time: 2 s, completed Apr 4, 2018 10:13:50 PM

3.

[info] Running ddbt.Compiler -l cpp -o bin/rs_streamvtable.hpp -c bin/rs_streamvtable.exe -x -xd bin -F -O3 -F -COMPILE-WITH-STATIC /usr/local/opt/dbtoaster/examples/queries/simple/rs_streamvtable.sql
[error] java.lang.RuntimeException: Type checking error: Type mismatch in map COUNT_mR1(int)[][s_b: int, s_c: int]<Local> of type int and RHS expression S(long)[][s_b: int, s_c: int]<Local> of type long
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$typeStmt$1(TypeCheck.scala:334)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at scala.collection.immutable.List.map(List.scala:284)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:347)
[error] 	at scala.collection.immutable.List.map(List.scala:288)
[error] 	at ddbt.frontend.TypeCheck$.typeCheck(TypeCheck.scala:347)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:372)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:12)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.Compiler$.codegen(Compiler.scala:366)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.lib.Utils$.ns(Utils.scala:40)
[error] 	at ddbt.Compiler$.compile(Compiler.scala:542)
[error] 	at ddbt.Compiler$.main(Compiler.scala:597)
[error] 	at ddbt.Compiler.main(Compiler.scala)
[error] 
[success] Total time: 2 s, completed Apr 4, 2018 10:16:38 PM

4.

[info] Running ddbt.Compiler -l cpp -o bin/query10.hpp -c bin/query10.exe -x -xd bin -F -O3 -F -COMPILE-WITH-STATIC /usr/local/opt/dbtoaster/examples/queries/tpch/query10.sql
[error] java.lang.RuntimeException: Type checking error: Type mismatch in map REVENUE_mCUSTOMER2(int)[][revenue_mcustomercustomer_nationkey: int, n_name: string]<Local> of type int and RHS expression AggSum([revenue_mcustomercustomer_nationkey: int, n_name: string],
[error]   NATION(long)[][revenue_mcustomercustomer_nationkey: int, n_name: string, n_regionkey: int, n_comment: string]<Local>
[error] ): long of type long
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$typeStmt$1(TypeCheck.scala:334)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29$$anonfun$apply$12.apply(TypeCheck.scala:349)
[error] 	at scala.collection.immutable.List.map(List.scala:284)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:349)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$29.apply(TypeCheck.scala:347)
[error] 	at scala.collection.immutable.List.map(List.scala:288)
[error] 	at ddbt.frontend.TypeCheck$.typeCheck(TypeCheck.scala:347)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at ddbt.frontend.TypeCheck$$anonfun$37.apply(TypeCheck.scala:370)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:372)
[error] 	at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:12)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error] 	at ddbt.Compiler$.codegen(Compiler.scala:366)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:542)
[error] 	at ddbt.lib.Utils$.ns(Utils.scala:40)
[error] 	at ddbt.Compiler$.compile(Compiler.scala:542)
[error] 	at ddbt.Compiler$.main(Compiler.scala:597)
[error] 	at ddbt.Compiler.main(Compiler.scala)
[error] 
[success] Total time: 3 s, completed Apr 4, 2018 10:20:31 PM

...few more

**Comment by losmi83** [comment] 2018-04-18 10:56
Hello, I cannot reproduce these problems with the latest committed version nor with the latest DBToaster binary v2.2. Have you tried updating your code?

**Comment by losmi83** [comment] 2018-04-18 17:08
I managed to reproduce this problem. The frontend is not up-to-date with the recent changes in the backend. Will be fixed soon.

**Comment by losmi83** [comment] 2018-04-20 16:01
The frontend is updated now.

**Closed by losmi83** 2018-04-20 16:01 UTC
